### ISSUE TITLE
Recommended configuration has to be usable always

### ISSUE THREAD

**Issue by dinogun** [kruize/autotune#1047]
As the recommended configuration is presented as a yaml to the user, if the yaml has empty fields, it renders it useless. Eg. If either of CPU or Memory recommendations cannot be generated while the other can be, it would be good to present a default for the resource for which a recommendation cannot be generated rather than a null value.

Explore what would be good default for each of the possible scenarios

**Comment by rbadagandi1** [comment]
Sample image for reference where we have memory recommendations (refer image.2) but nothing for CPU

![image](https://github.com/kruize/autotune/assets/137151710/2c111d43-6d38-47f9-976b-775851da2f7b)![image](https://github.com/kruize/autotune/assets/137151710/877535d8-183a-4318-9b57-936ad2ac4572)


In such cases, expectation is to set current CPU value as Recommended instead of Null.

**Comment by bharathappali** [comment]
Cases where we are not sending one of the two recommendations (CPU and Memory Recommendation) is:

- When the CPU is idle and we are not generating the recommendation
- When CPU / Memory recommendations are in threshold range wrt the current resource settings

**Comment by rbadagandi1** [comment]
Closing this since thsi was fixed as part of 20.3
