### ISSUE TITLE
Analyzer detects hotspot layer for a petclinic application that is based on OpenJ9

### ISSUE THREAD

**Issue by chandrams** [kruize/autotune#344]
Analyzer detects hotspot layer for a petclinic application that is based on OpenJ9

**Comment by ShishirH** [comment]
Can you please share the application image so I can test it out?

**Comment by chandrams** [comment]
You can use the petclinic manifests in kruize/benchmarks to deploy the petclinic with openj9.

**Comment by ShishirH** [comment]
Not able to reproduce this.

Deploying the petclinic-openj9 image using the scripts in the benchmark dir, give me this

```
[
  {
    "experiment_name": "petclinic-autotune-min-http-response-time",
    "experiment_id": "72410b4318bd78729e02dafce5f84e00cdebbdb9ea7c5ad7e4155eaa9d626193",
    "objective_function": "request_sum/request_count",
    "hpo_algo_impl": "optuna_tpe",
    "stacks": [
      {
        "deployment_name": "petclinic-sample-0",
        "layers": [
          {
            "layer_id": "8a881b57fe499431dde07d455246f1f43f860ce3f2a8e17d9d46851a1495ce6e",
            "layer_level": 0,
            "layer_name": "container",
            "layer_details": "generic container tunables"
          }
        ],
        "stack_name": "kruize/spring_petclinic:2.2.0-jdk-11.0.8-openj9-0.21.0"
      }
    ],
    "namespace": "default",
    "slo_class": "response_time",
    "direction": "minimize"
  }
]
```

**Comment by dinogun** [comment]
@ShishirH Not sure if you have the latest hotspot-micrometer-config.yaml. It currently has the query as `'jvm_memory_used_bytes{area="heap",}'`, which is actually too generic and picks up both hotspot and openj9 and it needs to be fixed.

I did this change earlier, due to another issue with the previous query that was referencing "Tenured Gen" `jvm_memory_used_bytes{area=\"heap\", id="Tenured Gen",}`. The issue with this is that, it takes a while for "Tenured Gen" to created as an object has to live long enough to get promoted to it. So if you run the query right after the application starts, this returns a null.

So, I think the solution here is to have an array of queries which can include, Eden, Tenured and other supported heap spaces in hotspot for all GCs and add only unique pod names returned by the set of queries. This way we will not miss any hotspot application, no matter what heap state it is in at any given moment.
